apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.variables.common.environment }}-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    name: {{ .Values.variables.common.environment }}-app
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
        - git:
            repoURL: {{ .Values.variables.common.gitRepo }}
            revision: {{ .Values.variables.common.revision }}
            files:
            - path: {{ .Values.variables.common.option }}/environments/{{ .Values.variables.common.environment }}/variables/values.yaml
        - list:
            elements: []
            elementsYaml: {{`"{{ .variables.products | toJson }}"`}}
  template:
    metadata:
      namespace: argocd
      name: {{`"{{ .variables.common.project }}-{{ .variables.common.environment }}-{{ .variables.common.type }}-{{ .product }}-{{ .productType }}-{{ .name }}"`}}
    spec:
      project: {{`"{{ .variables.common.project }}"`}}
      sources:
      - repoURL: {{`"{{ .variables.common.gitRepo }}"`}}
        targetRevision: {{`"{{ .variables.common.revision }}"`}}
        path: {{`"helm/{{ .chart }}"`}}
        helm:
          parameters:
            - name: image.tag
              value: {{`"{{ .appVersion }}"`}}
          valueFiles:
          - {{`"$values/{{ .variables.common.option }}/environments/{{ .variables.common.environment }}/products/{{ .product }}/{{ .name }}/values.yaml"`}}
      - repoURL: {{`"{{ .variables.common.gitRepo }}"`}}
        targetRevision: {{`"{{ .variables.common.revision }}"`}}
        ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: {{`"{{ .variables.common.project }}-{{.variables.common.environment }}-{{ .variables.common.type }}-{{.product }}-{{.productType }}"`}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata: 
          labels:
            project: {{`"{{ .variables.common.project }}-{{ .variables.common.environment }}-{{ .variables.common.type }}-{{.product}}-{{.productType }}"`}}
