variables:
  common:
    environment:    "100"
    project:        "project1"

  products:
    - name:         "product1-100-app1"
      product:      "product1"
      chart:        "app"
      appName:      "app1"
      appVersion:   "1.27.1-alpine-slim"
      syncWave:     "10"
    - name:         "product1-100-app2"
      product:      "product1"
      chart:        "app"
      appName:      "app2"
      appVersion:   "1.27.2-alpine-slim"
      syncWave:     "11"
    - name:         "product2-100-app1"
      product:      "product2"
      chart:        "app"
      appName:      "app1"
      appVersion:   "1.26.1-alpine-slim"
      syncWave:     "12"
    - name:         "product2-100-app2"
      product:      "product2"
      chart:        "app"
      appName:      "app2"
      appVersion:   "1.26.2-alpine-slim"
      syncWave:     "13"

  infrastructure:
    - name:         "infra-100-etcd"
      chart:        "etcd"
      repoUrl:      "registry-1.docker.io/bitnamicharts"
      chartVersion: "10.5.3"
      syncWave:     "1"
    - name:         "infra-100-etcd"
      chart:        "etcd"
      repoUrl:      "registry-1.docker.io/bitnamicharts"
      chartVersion: "10.5.3"
      syncWave:     "2"
    - name:         "infra-100-etcd"
      chart:        "etcd"
      repoUrl:      "registry-1.docker.io/bitnamicharts"
      chartVersion: "10.5.3"
      syncWave:     "3"
    #- name:         "infra-100-mongodb"
    #  chart:        "mongodb"
    #  repoUrl:      "registry-1.docker.io/bitnamicharts"
    #  chartVersion: "16.3.0"
